"""Regenerate static/js/world-land.js from Natural Earth 110m land polygons.

Usage: python scripts/generate_world_land.py
Requires: numpy, matplotlib (dev-only, not needed to run the app).
"""
import json
import math
import os
import urllib.request

import numpy as np
from matplotlib.path import Path

SOURCE_URL = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/"
    "geojson/ne_110m_land.geojson"
)
OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "static", "js", "world-land.js",
)

# Latitude spacing of the dot fill, in degrees. Longitude spacing is scaled by
# 1/cos(lat) so the dots stay evenly spread once wrapped onto the sphere.
DOT_STEP = 1.5
# Douglas-Peucker tolerance, in degrees, for the traced coastline rings.
OUTLINE_TOLERANCE = 0.35


def load_rings():
    with urllib.request.urlopen(SOURCE_URL) as resp:
        data = json.load(resp)
    rings = []
    for feat in data["features"]:
        geom = feat["geometry"]
        polys = [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]
        for poly in polys:
            rings.append([(x, y) for x, y in poly[0]])
    return rings


def simplify(points, eps):
    if len(points) < 3:
        return points
    pts = np.array(points)
    start, end = pts[0], pts[-1]
    line = end - start
    norm = float(np.hypot(*line))
    if norm == 0:
        dist = np.hypot(*(pts - start).T)
    else:
        offsets = pts - start
        dist = np.abs(line[0] * offsets[:, 1] - line[1] * offsets[:, 0]) / norm
    idx = int(np.argmax(dist))
    if dist[idx] > eps:
        return simplify(points[: idx + 1], eps)[:-1] + simplify(points[idx:], eps)
    return [points[0], points[-1]]


def build_dots(paths):
    dots = []
    lat = -84.0
    while lat <= 84.0:
        lng_step = DOT_STEP / max(math.cos(math.radians(lat)), 0.15)
        row = []
        lng = -180.0
        while lng < 180.0:
            row.append((lng, lat))
            lng += lng_step
        coords = np.array(row)
        inside = np.zeros(len(row), dtype=bool)
        for path in paths:
            inside |= path.contains_points(coords)
        for (lng_v, lat_v), is_land in zip(row, inside):
            if is_land:
                dots.extend([round(lat_v, 1), round(lng_v, 1)])
        lat += DOT_STEP
    return dots


def main():
    rings = load_rings()
    dots = build_dots([Path(np.array(r)) for r in rings])
    outlines = []
    for ring in rings:
        simple = simplify(ring, OUTLINE_TOLERANCE)
        if len(simple) < 4:
            continue
        outlines.append([v for x, y in simple for v in (round(y, 2), round(x, 2))])

    with open(OUT, "w") as f:
        f.write("// Generated by scripts/generate_world_land.py from Natural Earth\n")
        f.write("// 110m land polygons (public domain). Do not edit by hand.\n")
        f.write("// Flat [lat, lng, lat, lng, ...] arrays: LAND_DOTS fills the land\n")
        f.write("// masses, LAND_OUTLINES traces each coastline ring.\n")
        f.write("window.LAND_DOTS = " + json.dumps(dots, separators=(",", ":")) + ";\n")
        f.write("window.LAND_OUTLINES = " + json.dumps(outlines, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT}: {len(dots) // 2} dots, {len(outlines)} coastline rings")


if __name__ == "__main__":
    main()
